# Generated by Django 3.0.5 on 2020-05-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='quiestion',
            new_name='question',
        ),
    ]
